version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      _JAVA_OPTIONS: "-Xms512m -Xmx2048M -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -XX:ParallelGCThreads=1
                      -Djava.util.concurrent.ForkJoinPool.common.parallelism=1"
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "introduction/build.gradle" }}-{{ checksum "sample/build.gradle" }}
      - run:
          name: Create Licences
          command: echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_HOME/licenses/android-sdk-license &&
                   echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
      - run:
          name: Run Build
          command: ./gradlew build -Dorg.gradle.parallel=false -Dorg.gradle.daemon=false--max-workers 1 --console=plain
      - store_artifacts:
          path: introduction/build/reports
          destination: reports/introduction
      - store_artifacts:
          path: sample/build/reports
          destination: reports/sample
      - store_artifacts:
          path: sample/build/outputs/apk
          destination: apk
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "introduction/build.gradle" }}-{{ checksum "sample/build.gradle" }}
